Update WritingStyleGuide.rst for Extensions style
TYPO3-Documentation/TYPO3CMS-Guide-ContentAndMarketing pull request #14
Opened 2024-11-22 06:10 UTC by flicstar

2024-11-22 06:10 UTC, flicstar commented
@mabolek Please review and make changes. I added in a point about writing extension names in highly technical and procedural docs - do you think that is a context where using the key is acceptable?

2024-11-24 14:40 UTC, mabolek requested changes
Looks nice. I made some suggested adjustments.

2024-11-24 14:40 UTC, mabolek commented on Documentation/Content/WritingStyleGuide.rst
> +Where appropriate, on the first instance of the extension name in the text, we also include the link to the extension's page in the TYPO3 Extension Repository `(extensions.typo3.org) <https://extensi
```suggestion
Where appropriate, on the first instance of the extension name in the text, we also include the link to the extension's page in the `TYPO3 Extension Repository <https://extensions.typo3.org/>`__.
```

2024-11-24 14:40 UTC, mabolek commented on Documentation/Content/WritingStyleGuide.rst
> +On the first instance of the extension name in the text, we include the key in paranthesis immediately following the proper name. For example, "The AWS SDK for PHP (aws_sdk_php) extension...". You on
```suggestion
On the first instance of the extension name in the text, we include the key in paranthesis immediately following the proper name. For example, "The AWS SDK for PHP (aws_sdk_php) extension...".
```

2024-11-24 14:40 UTC, mabolek commented on Documentation/Content/WritingStyleGuide.rst
> +- Key: aws_sdk_php
```suggestion
* Name: AWS SDK for PHP
* Key: aws_sdk_php
```

2024-12-03 08:11 UTC, mabolek approved these changes

2024-12-03 08:12 UTC, merged